### ISSUE TITLE
[Bug] 웹소켓 패닉 처리 필요

### ISSUE THREAD

**Issue by JokerTrickster** [JokerTrickster/frog_mahjong_game#275]
## 에러 상세 정보
- 발생 시점 : 24/09/03
- 발견자 :  @JokerTrickster 
- 이슈 추적 방법 :   웹소켓에서 잘못 처리했을때 패닉이 발생하는데 잘못 처리라면 잘못된 메모리 주소 참조나 이런것들 서버가 다운이 되낟.
- 예상 원인 :웹소켓 패닉 처리 필요

panic: runtime error: index out of range [0] with length 0 | - | -
-- | -- | --
2024년 9월 03일 18:16 (UTC+9:00) | goroutine 24 [running]: | - | -
2024년 9월 03일 18:16 (UTC+9:00) | main/features/ws.CreateRoomInfoMSG({0x15196a0?, 0x40003dfef0?}, {0x4000388008, 0x0, 0x2?}, 0x1, 0x0) | - | -
2024년 9월 03일 18:16 (UTC+9:00) | /build/features/ws/usecase.go:84 +0x35c | - | -
2024년 9월 03일 18:16 (UTC+9:00) | main/features/ws.CloseEventWebsocket(0x40003925f0) | - | -
2024년 9월 03일 18:16 (UTC+9:00) | /build/features/ws/closeEventWebsocket.go:92 +0x23c | - | -
2024년 9월 03일 18:16 (UTC+9:00) | main/features/ws.WSHandleMessages() | - | -
2024년 9월 03일 18:16 (UTC+9:00) | /build/features/ws/websocket.go:30 +0x234 | - | -
2024년 9월 03일 18:16 (UTC+9:00) | created by main/features.InitHandler in goroutine 1 | - | -
2024년 9월 03일 18:16 (UTC+9:00) | /build/features/init.go:28 +0xd8

> 이슈 해결하기 위한 히스토리는 코멘트로 작성

### 코멘트 템플릿 
<pre> 
- 작업 시점 / 작업자 : 
- 파악된 원인 :
- 해결 방법 : 
- 해결 완료 여부 (미해결/해결완료): 
</pre>

**Comment by JokerTrickster** [comment]
패닉 원인으로는 방 나갔을때 타임아웃 설정 부분이 하드코어 되어 있어서 하드코어 부분 수정 완료
